---
- name: "Import Filebeat configurations file"
  notify: "Restart Filebeat"
  loop: "{{ add_filebeat_confs__inputs }}"
  loop_control:
    loop_var: input
  ansible.builtin.template:
    src: "templates/input.yml.j2"
    dest: "{{ add_filebeat_confs__path }}/{{ input.name | replace(' ', '-') }}.yml"
    mode: "0700"
    group: "{{ add_filebeat_confs__group }}"
    owner: "root"
    lstrip_blocks: yes
