---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.add_filebeat_confs"
      tags:
        - "labocbz.add_filebeat_confs"
      vars:
        add_filebeat_confs_path: "{{ inv_add_filebeat_confs_path }}"
        add_filebeat_confs_group: "{{ inv_add_filebeat_confs_group }}"
        add_filebeat_confs_ignore_older: "{{ inv_add_filebeat_confs_ignore_older }}"
        add_filebeat_confs_close_inactive: "{{ inv_add_filebeat_confs_close_inactive }}"
        add_filebeat_confs_inputs: "{{ inv_add_filebeat_confs_inputs }}"
      ansible.builtin.include_role:
        name: "labocbz.add_filebeat_confs"
